
export const categoryConstants = {
    CATEGORY_REQUEST: "CATEGORY_REQUEST",
    CATEGORY_SUCCESS:"CATEGORY_SUCCESS",
    CATEGORY_FAILURE: "CATEGORY_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
}
